---
platform: linux

image: docker:///bosh/init

inputs:
  - name: bosh-vsphere-stemcell-version
  - name: bosh-agent-zip
  - name: bosh-agent-deps-zip
  - name: ovftool-linux
  - name: stemcell-builder

outputs:
  - name: vagrant_home
  - name: bosh-vsphere-stemcell

run:
  path: stemcell-builder/scripts/create-vsphere-stemcell-windows.sh

params:
  VCENTER_HOST: replace-me
  VCENTER_COMPUTE_RESOURCE: replace-me
  VCENTER_DATACENTER: replace-me
  VCENTER_RESOURCE_POOL: replace-me
  VCENTER_TEMPLATE_NAME: replace-me
  VCENTER_PASSWORD: replace-me
  VCENTER_USERNAME: replace-me
  VCENTER_FINGERPRINT: replace-me
  VCENTER_VM_BASE_PATH: replace-me
  VCENTER_VM_NAME: replace-me
  WINRM_PASSWORD: replace-me
  WINRM_USERNAME: replace-me
  VAGRANT_HOME: replace-me
  VAGRANT_DOTFILE_PATH: replace-me
  VAGRANT_VAGRANTFILE: replace-me
