---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalgreenhouse/packer-base

inputs:
  - name: windows-ami
  - name: bosh-agent-zip
  - name: bosh-agent-deps-zip
  - name: version
  - name: bosh-agent
  - name: stemcell-builder

outputs:
  - name: bosh-windows-stemcell

run:
  path: stemcell-builder/scripts/create-aws-stemcell.rb

params:
  OUTPUT_DIR: replace-me
  AWS_ACCESS_KEY: replace-me
  AWS_SECRET_KEY: replace-me
  VPC_ID: replace-me
  SUBNET_ID: replace-me
