---
platform: linux

image: docker:///bosh/init

inputs:
  - name: windows-ami
  - name: bosh-agent-zip
  - name: bosh-agent-deps-zip
  - name: version
  - name: bosh-agent
  - name: stemcell-builder

outputs:
  - name: bosh-aws-stemcell

run:
  path: stemcell-builder/tasks/create-aws-stemcell.rb

params:
  OUTPUT_DIR: replace-me
  AWS_ACCESS_KEY: replace-me
  AWS_SECRET_KEY: replace-me
  VPC_ID: replace-me
  SUBNET_ID: replace-me
