---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalgreenhouse/packer-base

inputs:
  - name: stemcell-regions
  - name: bosh-agent-sha
  - name: bosh-agent-zip
  - name: bosh-agent-deps-zip
  - name: version
  - name: stemcell-builder

outputs:
  - name: bosh-windows-stemcell
  - name: amis

run:
  path: stemcell-builder/scripts/create-aws-stemcell.rb
